Add pkgs

diff --git a/out/hanhbuild b/out/hanhbuild
--- a/out/hanhbuild
+++ b/out/hanhbuild
@@ -165,7 +165,7 @@ if test -f "$hanhdir"/"$tarball"; then
 fi
 
 if test -n "$clean"; then
-	rm -rf "$pkgdir" "$workdir" "$hanhdir"/.buildinfo "$hanhdir"/"$tarball" "$hanhdir"/deps
+	rm -rf "$pkgdir" "$workdir" "$hanhdir"/.buildinfo "$hanhdir"/"$tarball" "$hanhdir"/deps "$hanhdir"/asked
 fi
 
 rm -rf "$pkgdir"
@@ -220,7 +220,49 @@ if test -n "$repack"; then
 	tar -cJf "$hanhdir"/"$tarball" *	
 	echo "Package $tarball created."
 fi
-} 
+}
+
+ask() {
+cwd=$(pwd)
+read -r package
+pkg=$(echo $package | cut -d " " -f 1)
+for x in $*; do 
+	if test "$pkg" = "$x"; then
+		found=1
+		mkdir -p asked 
+		cd asked
+		if test "$pkg" != "$name"; then 
+			fetch_pkg $pkg 
+			cd $pkg 
+			hanhbuild -b $misc || exit 1
+		else
+			echo "Building the package with the same name"
+			hanhbuild -bf=$hanhdir/buildhanh.$name -b $misc || exit 1
+		fi	
+
+		mv *hanhpkg* $cwd 
+		cd $cwd
+	
+	fi
+done
+
+if test -z $found; then 
+	echo "Package name $package not found! Re-enter again" 
+	ask $* 
+fi
+}
+
+ask_pkg() {
+echo "Available packages are: $*"
+echo "Please enter one below"
+ask $*
+}
+
+define_ask() {
+ver=9999
+desc="Ask for $name providers"
+task="pkgask"
+}
 
 . //etc/hanh.conf || die "Cannot get information from configuration file."
 
@@ -232,10 +274,10 @@ for arg in $*; do
 		-F) action=fetch_pkg;;
 		-g) action=gen_db;;
 		-gf) action=get_flag;;
-		-d) nodeps=1;;
-		-f) force=1;;
-		-c) clean=1;;
-		-bd) builddeps=1;;
+		-d) export nodeps=1;;
+		-f) export force=1;;
+		-c) export clean=1;;
+		-bd) export builddeps=1;;
 		-s=*) SYSROOT="$(echo $arg | cut -d "=" -f 2)";;
 		-bf=*) buildfile="$(echo $arg | cut -d "=" -f 2)";;
 		-t=*) Task="$(echo $arg | cut -d "=" -f 2 | sed 's/,/ /g')";;
